training:
  project_name: gen_names
  train_name: mamba
  seed: 1702
  epochs: 300
  batch: 256
  lr: 3e-4
  model_path: /weights
  wandb_path: /wandb
  save_best_of: 3
  checkpoint_monitor: val_loss
  early_stopping_patience: 50

data:
  data_directory: datasets/names
  chunk_size: 10