training:
  project_name: gen_names
  train_name: true_mamba
  seed: 1702
  epochs: 30
  batch: 1024
  lr: 3e-6
  model_path: ${hydra:run.dir}/weights
  wandb_path: ${hydra:run.dir}/wandb
  save_best_of: 3
  checkpoint_monitor: val_loss
  early_stopping_patience: 8

data:
  data_directory: datasets/names
  chunk_size: 10

generation:
  temperature: 0.5
  alpha: 0.05
  train_reweight: False
  val_reweight: True
  beamsize: 5